# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    get_certificates           # invokes cert
    get_provisioning_profile
    match(type:"adhoc")
    build_app(
      scheme: "test",
      export_method: "ad-hoc"
      )
   
  end
lane :beta2 do
  build_app(
    export_method: "ad-hoc",
    export_options: {
      provisioningProfiles: { 
        "com.tsingzone.questionbankTest" => "17_teacher_test_ad_hoc",
      }
    }
  )
  pgyer(api_key:"e6b5455a4729b99986a89abb69d78f77",user_key:"01726b71aa9e038c877d24e1e7b47275")
end
end
